# Generated by Django 5.1.2 on 2024-10-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0002_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
    ]
